# Rules
windowrule = float on,match:title iwgtk
windowrule = float on,match:title Volume Control
windowrule = float on,match:class org.gnome.NautilusPreviewer

# Picture-in-Picture
windowrule = float on, max_size 1080 720, opaque on, keep_aspect_ratio on, match:title Picture in picture
windowrule = float on, max_size 1080 720, opaque on, keep_aspect_ratio on, match:title Picture-in-Picture
windowrule = pin on,match:title Picture-in-Picture
