# Essential UI
exec-once = dbus-launch dms run
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 
exec-once = foot --server
exec-once = kdeconnectd
exec = xrdb -merge ~/.Xresources

