# Essential UI
exec-once = dbus-launch waybar 
exec-once = dunst 
exec-once = hypridle 
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 
exec-once = kdeconnect-indicator 
exec-once = emacs --daemon 
exec-once = swww-daemon --no-cache 
exec-once = swww img $(cat ~/.cache/cwal/cwal) -t none
exec = xrdb -merge ~/.Xresources

# Clipboard
exec-once = cliphist wipe
exec-once = wl-paste --watch cliphist store

# Default apps
exec-once = xdg-mime default org.gnome.Loupe.desktop image/jpeg image/png image/heic
exec-once = xdg-mime default qutebrowser-profile.desktop text/html x-scheme-handler/http x-scheme-handler/https
exec-once = xdg-mime default org.gnome.Nautilus.desktop inode/directory
