$terminal = foot
$fileManager = pcmanfm
$menu = dms ipc spotlight toggle
$clipboard_ui = dms ipc clipboard toggle
$lock = dms ipc lock lock
$browser = helium-browser
$editor = emacsclient -c  -a emacs
$music = $terminal rmpc
$main_menu = dms ipc dankdash wallpaper
$power_menu = dms ipc powermenu toggle
