$terminal = foot 
$fileManager = pcmanfm
$menu = rofi -show drun
$clipboard_ui = cliphist list | rofi -dmenu | cliphist decode | wl-copy
$browser = glide-bin  
$editor = emacsclient -c  -a emacs
$music = $terminal rmpc
$main_menu = ~/.config/hypr/scripts/hyprmain
$notes = ~/.config/scripts/notes
$websearch = ~/.config/scripts/websearch
$connect = ~/.config/scripts/connect
