source=./modules/animations.conf
source=./modules/appearence.conf
source=./modules/autostart.conf
source=./modules/env.conf
source=./modules/input.conf
source=./modules/keybinds.conf
source=./modules/rules.conf

source=./dms/colors.conf
source=./dms/outputs.conf
source=./dms/cursor.conf
