# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x121317ff
bordercolor = 0x8d919aff
dropcolor = 0xa8c8fe80
splitcolor = 0xecb4ebff
focuscolor = 0xa8c8feff
maximizescreencolor = 0xbbc7dfff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xecb4ebff
globalcolor = 0x7292c5ff
overlaycolor = 0x3c475bff
jump_label_decorate_fg_color = 0xe3e2e6ff
jump_label_decorate_bg_color = 0x292a2dff
jump_label_decorate_focus_fg_color = 0x05305eff
jump_label_decorate_focus_bg_color = 0xa8c8feff
jump_label_decorate_border_color = 0x8d919aff
group_bar_decorate_fg_color = 0xe3e2e6ff
group_bar_decorate_bg_color = 0x292a2dff
group_bar_decorate_focus_fg_color = 0x05305eff
group_bar_decorate_focus_bg_color = 0xa8c8feff
group_bar_decorate_border_color = 0x8d919aff
