gesture swipe up 3 wtype -M logo -k a
gesture swipe down 3 wtype -M logo -k g

gesture swipe left 3 wtype -M logo -k j
gesture swipe right 3 wtype -M logo -k k

gesture swipe left 4 wtype -M logo -M shift -k h
gesture swipe right 4 wtype -M logo -M shift -k l

