# layers
layer_animations=1
layer_animation_type_open=fade
layer_animation_type_close=fade

# windows
animation_type_open=slide
animation_type_close=slide
animation_duration_open=300
animation_duration_move=300
animation_duration_tag=200
animation_curve_open=0.16, 1, 0.3, 1
animation_curve_move=0.16, 1, 0.3, 1
animation_curve_tag=0.16, 1, 0.3, 1
