# --- Window & Animation Effects ---
blur=4
blur_layer=1
blur_optimized=1
blur_params_num_passes = 3
blur_params_radius = 3
border_radius=10
focused_opacity=0.9
unfocused_opacity=0.7

hotarea_size=2

# --- Appearance & Layout ---
gappih=5
gappiv=5
gappoh=10
gappov=10
borderpx=2
