# --- Window & Animation Effects ---
blur=2
blur_layer=2
blur_optimized=1
blur_params_num_passes = 3
blur_params_radius = 3
focused_opacity=0.8
unfocused_opacity=0.7

hotarea_size=2

# --- Cursors ---
cursor_size=32
cursor_theme=macOS

# --- Appearance & Layout ---
gappih=8
gappiv=8
gappoh=10
gappov=10
borderpx=4
border_radius=16
