exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = swayidle
exec-once = dms run
exec-once = dunst
exec-once = awww-daemon 
exec-once = emacs --daemon
exec-once = wl-paste --watch cliphist store
exec-once = waybar
