exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start xdg-desktop-portal-wlr xdg-desktop-portal
exec-once = dms run
exec-once = swayidle
exec-once = emacs --daemon
exec-once = yams
