exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start xdg-desktop-portal-wlr xdg-desktop-portal
exec-once = swayidle
exec-once = dunst
exec-once = swaybg -i $(<~/.cache/ashwal/ashwal) -m fill 
exec-once = emacs --daemon
exec-once = wl-paste --watch cliphist store
exec-once = waybar
