# keyboard
repeat_rate=25
repeat_delay=600
numlockon=0
xkb_rules_layout=us
xkb_rules_variant=colemak_dh

# Trackpad
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=0
disable_while_typing=1
scroll_method=1
middle_button_emulation=1
swipe_min_threshold=20

# Gestures
# 3-finger: Window focus
gesturebind=none,left,3,focusdir,left
gesturebind=none,right,3,focusdir,right
gesturebind=none,up,3,togglemaximizescreen
gesturebind=none,down,3,togglefloating

# 4-finger: Workspace navigation
gesturebind=none,left,4,viewtoleft
gesturebind=none,right,4,viewtoright
gesturebind=none,up,4,toggleoverview
gesturebind=none,down,4,toggleoverview
