# Launchers
bind=SUPER,space,spawn,rofi -show drun
bind=SUPER,Return,spawn,foot
bind=SUPER,v,spawn_shell,cliphist list | rofi -dmenu | cliphist decode | wl-copy
bind=SUPER,u,spawn,gtklock
bind=SUPER,t,spawn,zen-browser
bind=SUPER,e,spawn,thunar
bind=SUPER,w,spawn,emacsclient -c -a emacs
bind=SUPER,p,spawn,connect
bind=SUPER,m,spawn,foot rmpc
bind=SUPER+CTRL,space,spawn,walmenu
bind=SUPER+SHIFT,Slash,spawn,silly

# Session & Window Management
bind=SUPER,r,reload_config
bind=SUPER+SHIFT,q,spawn,quit
bind=SUPER,q,killclient
bind=SUPER,Tab,toggleoverview
bind=SUPER,f,togglefullscreen
bind=SUPER,g,togglefloating
bind=SUPER,a,togglemaximizescreen
bind=SUPER,d,toggleglobal,

# Navigation (Focus)
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down

bind=SUPER+ALT,h,viewtoleft
bind=SUPER+ALT,l,viewtoright

# Tag Switching
bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9

# Move Window to Tag
bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9

# Resize Windows
bind=SUPER+CTRL,k,resizewin,+0,-50
bind=SUPER+CTRL,j,resizewin,+0,+50
bind=SUPER+CTRL,h,resizewin,-50,+0
bind=SUPER+CTRL,l,resizewin,+50,+0

# Move Windows
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right

# Layouts
bind=SUPER,n,switch_layout
bind=SUPER,z,setlayout,tgmix
bind=SUPER,x,setlayout,scroller
bind=SUPER,c,setlayout,grid

# Mouse Button Bindings
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# Audio Controls
bind=NONE,XF86AudioRaiseVolume,spawn,osd volume 5%+
bind=NONE,XF86AudioLowerVolume,spawn,osd volume 5%-
bind=NONE,XF86AudioMute,spawn,osd volume mute

# Brightness Controls
bind=NONE,XF86MonBrightnessUp,spawn,osd brightness 5%+
bind=NONE,XF86MonBrightnessDown,spawn,osd brightness 5%-

# Screenshot Keys
bind=NONE,Print,spawn_shell,screenshot clip
bind=CTRL,Print,spawn_shell,screenshot
bind=SHIFT,Print,spawn_shell,screenshot ocr
bind=CTRL+SHIFT,Print,spawn_shell,screenshot color
