windowrule=isterm:1,appid:foot
windowrule=isfloating:1,isglobal:1,title:Picture-in-Picture
windowrule=isfloating:1,isglobal:1,title:Picture in picture
windowrule=isfloating:1,appid:firefox,title:"Firefox - Choose User Profile"
windowrule =isfloating;1,title:^(Android Emulator.*)$

layerrule=noblur:1,layer_name:selection
layerrule=animation_type_open:zoom,animation_type_close:zoom,noanim:0,layer_name:rofi
layerrule=noanim:1,noshadow:1,layer_name:dunst

layerrule=noanim:1,noblur:1,layer_name:^dms
windowrule=isfloating:1,appid:^org\.quickshell$

tagrule=id:1,layout_name:fair
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:fair
tagrule=id:4,layout_name:fair
tagrule=id:5,layout_name:fair
tagrule=id:6,layout_name:fair
tagrule=id:7,layout_name:fair
