[ids]
*

[global]
hold_timeout = 200
idle_timeout = 300

[main]
capslock = overload(control, esc)
# Syntax: lettermod(layer, key, idle_timeout, hold_timeout)
a = lettermod(alt, a, 150, 150)
s = lettermod(shift, s, 150, 150)
d = lettermod(control, d, 150, 150)
f = lettermod(meta, f, 150, 150)

j = lettermod(meta, j, 150, 150)
k = lettermod(control, k, 150, 150)
l = lettermod(shift, l, 150, 150)
; = lettermod(alt, ;, 150, 150)

# --- Bottom Row Layer Triggers ---
leftcontrol = noop 
leftshift = layer(media)
leftmeta = layer(system)
leftalt = layer(manipulation)
rightalt = layer(manipulation)
rightmeta = overload(none, none)
rightcontrol = layer(media)

[manipulation]
q = delete
e = backspace
r = C-tab
f = meta

w = up
a = left
s = down
d = right

j = left
k = down
l = up
; = right
' = enter

[media]
q = mute
w = volumeup
e = playpause
a = previoussong
s = volumedown
d = nextsong

[system]
w = brightnessup
s = brightnessdown

[disable]
# This is a "dead" layer. In keyd, we leave it empty or map keys to 'noop'
