general {
    lock_cmd = ~/.config/scripts/lock.sh       # what to run to lock
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    # Use mmsg to ensure the monitor is enabled on wake
    after_sleep_cmd = mmsg -d enable_monitor,eDP-1 
}

listener {
    timeout = 300                                # 5 mins
    on-timeout = loginctl lock-session           # lock screen
}

listener {
    timeout = 330                                # 5.5 mins
    # Native MangoWC command to turn off screen
    on-timeout = mmsg -d disable_monitor,eDP-1       
    # Native MangoWC command to turn on screen
    on-resume = mmsg -d enable_monitor,eDP-1         
}
