###################
### Hyprland ###
###################
source = ./modules/variables.conf
source = ./modules/autostart.conf
source = ./modules/env.conf
source = ./modules/looks.conf
source = ./modules/animations.conf
source = ./modules/input.conf
source = ./modules/keybinds.conf

##############################
###   Dank Material Shell  ###
##############################
source = ./dms/outputs.conf
source = ./dms/cursor.conf
source = ./dms/windowrules.conf
source = ./dms/layout.conf
source = ./dms/colors.conf
