import ~/.cache/ashwal/colors-nauka.conf
#import noctalia.conf

# Autostart
run waybar
run "swaybg -i $(<~/.cache/ashwal/ashwal) -m fill"
run dunst
run "wl-paste --watch cliphist store"
run ~/.local/bin/yams
run swayosd-server
run kdeconnectd
run "easyeffects --w"

# ENV
env QT_QPA_PLATFORMTHEME qt6ct

# Border
border_width 3

outer_gap 16
inner_gap 10

# Inputs
focus_follows_mouse true
keyboard_layout us
keyboard_variant colemak_dh

cursor_theme macOS
cursor_size 32

# Eye Candy
border_radius 0
opacity_active 0.8
opacity_inactive 0.7

blur true
blur_strength 4.0
blur_alpha 1


default_layout scroller

# Misc
xwayland 1

# Keybinds
keybind super return run ghostty
keybind alt return run kitty
keybind super space run "rofi -show drun -show-icons"
keybind super b run "flatpak run app.zen_browser.zen"
keybind super f run dolphin
keybind super w run "emacsclient -c -a emacs"
keybind super h run "flatpak run com.github.taiko2k.tauonmb"
keybind super v run "cliphist list | rofi -dmenu | cliphist decode | wl-copy"
keybind super q kill_active
keybind super n prev_toplevel
keybind super e next_toplevel
keybind super+shift n swap_prev_toplevel
keybind super+shift e swap_next_toplevel
keybind super r reload
keybind alt r reload
keybind super g toggle_floating
keybind super s toggle_sticky
keybind super a toggle_fullscreen
keybind super x layout grid
keybind super c layout master
keybind super z layout scroller
keybind super equal grow_focused
keybind super minus shrink_focused
keybind super+shift q exit

keybind super pointer_left_click move
keybind super pointer_right_click resize

# View tags
keybind super 1 view_tag
keybind super 2 view_tag
keybind super 3 view_tag
keybind super 4 view_tag
keybind super 5 view_tag
keybind super 6 view_tag
keybind super 7 view_tag
keybind super 8 view_tag
keybind super 9 view_tag

# Move focused window to tag
keybind super+shift 1 move_focused_to_tag
keybind super+shift 2 move_focused_to_tag
keybind super+shift 3 move_focused_to_tag
keybind super+shift 4 move_focused_to_tag
keybind super+shift 5 move_focused_to_tag
keybind super+shift 6 move_focused_to_tag
keybind super+shift 7 move_focused_to_tag
keybind super+shift 8 move_focused_to_tag
keybind super+shift 9 move_focused_to_tag

# Brightness
keybind _ XF86MonBrightnessUp   run "swayosd-client --brightness raise"
keybind _ XF86MonBrightnessDown run "swayosd-client --brightness lower"

# Volume
keybind _ XF86AudioRaiseVolume run "swayosd-client --output-volume +2 --max-volume 150"
keybind _ XF86AudioLowerVolume run "swayosd-client --output-volume -2 --max-volume 150"

# Mute
keybind _ XF86AudioMute         run "swayosd-client --output-volume mute-toggle"
keybind _ XF86AudioMicMute      run "swayosd-client --input-volume mute-toggle"

keybind _ Print run "~/.local/bin/screenshot clip"
keybind ctrl Print run "~/.local/bin/screenshot"
keybind ctrl+shift Print run "~/.local/bin/screenshot ocr"
