import ~/.cache/ashwal/colors-nauka.conf

# Autostart
run "swaybg -i $(<~/.cache/ashwal/ashwal) -m fill"
run waybar
run dunst
run ~/.local/bin/yams
run kdeconnectd
run cosmic-settings-daemon
run cosmic-osd

# Keybinds
keybind super return run ghostty
keybind alt return run kitty
keybind super space run "rofi -show drun -show-icons"
keybind super t run "flatpak run app.zen_browser.zen"
keybind super e run nautilus
keybind super w run "emacs"
keybind super m run "flatpak run com.github.taiko2k.tauonmb"
keybind super comma run "cosmic-settings"
keybind alt+shift escape run "cosmic-monitor"
keybind super q kill_active
keybind super n next_toplevel
keybind super r reload
keybind alt r reload
keybind super g toggle_floating
keybind super a toggle_fullscreen
keybind super+shift q exit

keybind super pointer_left_click move
keybind super pointer_right_click resize

# View tags
keybind super 1 view_tag
keybind super 2 view_tag
keybind super 3 view_tag
keybind super 4 view_tag
keybind super 5 view_tag
keybind super 6 view_tag
keybind super 7 view_tag
keybind super 8 view_tag
keybind super 9 view_tag

# Move focused window to tag
keybind super+shift 1 move_focused_to_tag
keybind super+shift 2 move_focused_to_tag
keybind super+shift 3 move_focused_to_tag
keybind super+shift 4 move_focused_to_tag
keybind super+shift 5 move_focused_to_tag
keybind super+shift 6 move_focused_to_tag
keybind super+shift 7 move_focused_to_tag
keybind super+shift 8 move_focused_to_tag
keybind super+shift 9 move_focused_to_tag

# Screenshot, Volume and Brightness
keybind _ XF86MonBrightnessUp run "brightnessctl set +5%"
keybind _ XF86MonBrightnessDown run "brightnessctl set 5%-"

keybind _ XF86AudioRaiseVolume run "wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"
keybind _ XF86AudioLowerVolume run "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"

keybind _ XF86AudioMute run "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
keybind _ XF86AudioMicMute run "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"

keybind _ Print run "~/.local/bin/screenshot clip"
keybind ctrl Print run "~/.local/bin/screenshot"
keybind ctrl+shift Print run "~/.local/bin/screenshot ocr"

# Border
border_width 3

outer_gap 18
inner_gap 10

# Inputs
tap_to_click true
natural_scroll true
disable_while_typing true
left_handed false
pointer_accel 0.3
scroll_method two_finger

pointer "DELL0A20:00 0488:101A Touchpad" 1 0.3

# Eye Candy
border_radius 16
opacity_active 0.8
opacity_inactive 0.7

blur true
blur_strength 4.0
blur_alpha 1
