#!/usr/bin/env python3

import random
import subprocess

quotes = [
    ("Through goes Hamilton", "David Croft"),
    ("Simply lovely", "Du Du Du Max Verstappen"),
    ("We are checking", "Ferrari Mechanics xD"),
    ("Must be the water", "The Prince of Monoco, Charles Leclerc"),
    ("Ki ki rahh!", "Daniel Ricciardo"),
    ("Smooth operator", "Carlos Sainz"),
    ("Multi 21 Seb.", "Mark Webber"),
    ("Leave me alone, I know what I'm doing!", "The Iceman, Kimi Räikkönen"),
    ("No, Michael, no, no! That was so not right!", "Toto Wolff"),
    ("Valteri, its James.", "James Vowels"),
    ("I am stupid.", "Charles Leclerc"),
    ("Look like a bunch of w*nkers.", "Guenther Steiner"),
    ("Is that Glock?! Slowing Down?", "James Allen"),
    ("GP2 engine, GP2... ARGH!", "Fernando Alonso"),
    ("Sebastian Vettel, YOU ARE THE WORLD CHAMPION!", "Christian Horner"),
    ("Everyone is a Ferrari fan. Even if they're not, they are Ferrari fans.", "Sebastian Vettel"),
    ("Ring-ding-ding-ding-ding!", "The Vettel Finger Celebration")
]

fonts = ["future", "smblock", "ascii9", "ascii12", 
         "bigmono9", "letter", "smmono9", "wideterm", "pagga"]

def main():
    quote, author = random.choice(quotes)
    font = random.choice(fonts)
    
    print()
    try:
        subprocess.run(["toilet", "-f", font, "-t", quote])
    except FileNotFoundError:
        try:
            subprocess.run(["figlet", "-f", "slant", quote])
        except FileNotFoundError:
            print(f'  "{quote}"')
    
    print(f"\n    — {author}\n")

if __name__ == "__main__":
    main()
