#!/usr/bin/env python3

import random
import subprocess

quotes = [
    ("Through goes Hamilton", "David Croft"),
    ("Simply lovely", "Du Du Du Max Verstappen"),
    ("We are checking", "Ferrari Mechanics xD"),
    ("Must be the water", "The Prince of Monoco, Charles Leclerc"),
    ("Ki ki rahh!", "Daniel Ricciardo"),
    ("Smooth operator", "Carlos Sainz"),
    ("Multi 21 Seb.", "Mark Webber"),
]

fonts = ["future", "smblock", "ascii9", "ascii12",
         "bigmono9", "letter", "smmono9", "wideterm", "pagga"]

random.shuffle(quotes)
random.shuffle(fonts)

quote, author = quotes[0]
font = fonts[0]
print()
try:
    subprocess.run(["toilet", "-f", font, "-t", quote])
except FileNotFoundError:
    try:
        subprocess.run(["figlet", "-f", "slant", quote])
    except FileNotFoundError:
        print(f'  "{quote}"')
print(f"    — {author}")
print()
