#!/bin/sh

# Prints the current volume or mute if muted.

case $BLOCK_BUTTON in
	1) setsid -w -f pavucontrol; pkill -RTMIN+10 "${STATUSBAR:-dwmblocks}" ;;
	2) wpctl set-mute @DEFAULT_SINK@ toggle ;;
	4) wpctl set-volume @DEFAULT_SINK@ 1%+ ;;
	5) wpctl set-volume @DEFAULT_SINK@ 1%- ;;
	3) notify-send "Volume module" "\- Shows volume, mute if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) setsid -f kitty -e "$EDITOR" "$0" ;;
esac

vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

# If muted, print mute and exit.
[ "$vol" != "${vol%\[MUTED\]}" ] && echo mute && exit

vol="${vol#Volume: }"

split() {
	# For ommiting the . without calling and external program.
	IFS=$2
	set -- $1
	printf '%s' "$@"
}

vol="$(printf "%.0f" "$(split "$vol" ".")")"

echo "$vol%"
