#!/usr/bin/env bash

FOLDER=~/Pictures/Wallpapers/
SCRIPT=walup

# 1. Select the Wallpaper
if command -v nsxiv >/dev/null; then 
    WALLPAPER=$(nsxiv -otb "$FOLDER"/*)
else 
    CHOICE=$(command ls -v "$FOLDER" | rofi -dmenu -c -l 15 -i -p "Wallpaper: ")
    [ -z "$CHOICE" ] && exit 0
    WALLPAPER="$FOLDER/$CHOICE"
fi

[ -z "$WALLPAPER" ] && exit 0

wal -i "$WALLPAPER" -o "$SCRIPT" 2>/dev/null

