#!/bin/bash

# update bg
feh --bg-fill $(cat ~/.cache/wal/wal) &
xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitoreDP-1/workspace0/last-image -s $(cat ~/.cache/wal/wal)

# update xrdb
xrdb -load ~/.Xresources

# update qutebrowser colors
~/.config/scripts/qute-reload &

# update emacs colors
emacsclient -e '(my/reload-xresources-theme)' &

# update firefox colors
pywalfox update &

# update kitty colors
pkill -SIGUSR1 kitty

# update dunst colors
pkill dunst &
dunst & disown

# update qute-reload colors
qute-reload &

# update xfce4
xfce4-panel -r &
pkill xfwm4 &
