#!/bin/bash

# update bg
feh --bg-fill $(cat ~/.cache/cwal/cwal) &
swaybg -i $(cat ~/.cache/cwal/cwal) -m fill &

# update xrdb
xrdb -load ~/.Xresources

# update emacs colors
emacsclient -e '(my/reload-xresources-theme)' &

# update firefox colors
pywalfox update &

# update kitty colors
pkill -SIGUSR1 kitty

# update dunst colors
pkill dunst &
dunst &
disown

# update qute-reload colors
qute-reload &

# update cosmic colors
cosmic-settings appearance import ~/.cache/wal/colors-cosmic.ron
