#!/bin/bash

# update bg
pkill swaybg
swaybg -i $(cat ~/.cache/ashwal/ashwal) -m fill &

# update xrdb
xrdb -load ~/.Xresources

# update emacs colors
emacsclient -e '(my/reload-xresources-theme)' &

# update kitty colors
pkill -SIGUSR1 kitty

# update dunst colors
pkill dunst &
dunst & disown

# update qute-reload colors
qute-reload &
